# 테이블 생성
CREATE TABLE STUDENT_LIST (
	NO INTEGER NOT NULL,
    NAME VARCHAR(20)
    );
    
    
# 만든 테이블로 실행
SELECT * FROM STUDENT_LIST;
ALTER TABLE STUDENT_LIST ADD BIRTH DATE;


# BIRTH 컬럼 타입을 VARCHAR(20)으로 수정
ALTER TABLE STUDENT_LIST MODIFY BIRTH VARCHAR(20);
DESC STUDENT_LIST;


# BIRTH 컬럼의 이름을 BIRTHDAY로 변경
# CHANGE 기준열 바꿀이름 기존타입
ALTER TABLE STUDENT_LIST CHANGE BIRTH BIRTHDAY VARCHAR(20);


# 제약조건 : NOT NULL = 해당열에 NULL값을 인정하지 않을 거야.
# BIRTHDAY열에 NOT NULL 조건을 추가 (조건을 수정)
ALTER TABLE STUDENT_LIST MODIFY BIRTHDAY VARCHAR(20) NOT NULL;
DESC STUDENT_LIST;


# NOT NULL을 없애고 싶다. (조건을 수정)
ALTER TABLE STUDENT_LIST MODIFY BIRTHDAY VARCHAR(20);
DESC STUDENT_LIST;


# BIRTHDAY VARCHAR -> BIRTH DATE
# 이름과 속성을 동시에 변경하려면, CHANGE 기존열 바꿀이름 바꿀속성
ALTER TABLE STUDENT_LIST CHANGE VIRTHDAY BIRTH DATE;


# DROP TABLE 테이블명


# INDEX 생성 (인덱스 생성은 매우매우 중요하다!)
CREATE INDEX STUDENT_INDEX ON STUDENT_LIST(NO);
SELECT * FROM STUDENT_LIST;
INSERT INTO STUDENT_LIST VALUES (1, 'ARDINO', '2020-06-15'), (2, 'ONDS', '2020-06-16');


# 인덱스 확인
EXPLAIN SELECT * FROM STUDENT_LIST WHERE NO > 1;


# 인덱스 삭제
DROP INDEX STUDENT_INDEX ON STUDENT_LIST;
EXPLAIN SELECT * FROM STUDENT_LIST WHERE NO > 1;



