# insert

SHOW databases;
USE SAKILA;
SELECT database();
SHOW tables;
SELECT * FROM PAYMENT;
INSERT INTO PAYMENT(PAYMENT_ID) VALUES(1001);

SHOW TABLES;
SELECT * FROM TEST_NEW_TABLE;
INSERT INTO TEST_NEW_TABLE VALUES(0, 'SMART');
SHOW TABLES;
SELECT * FROM TEST_NEW_TABLE;
INSERT INTO TEST_NEW_TABLE VALUES(1, 'SMART');
SELECT * FROM TEST_NEW_TABLE;
INSERT INTO TEST_NEW_TABLE VALUES(2, 'SMART'), (3, 'SMART'), (4, 'SMART'), (5, 'SMART');

DELETE FROM TEST_NEW_TABLE WHERE ID =4;
DELETE FROM TEST_NEW_TABLE LIMIT 1;
-- DELETE FROM TEST_NEW_TABLE ORDER BY; # 할 필요가 없다. 사용하지 않는다.
-- DELETE FROM TEST_NEW_TABLE LIMIT 1 OFFSET; # 할 필요가 없다. 사용하지 않는다.
DELETE FROM TEST_NEW_TABLE;
TRUNCATE TEST_NEW_TABLE;  # 모두 삭제 : 파이썬 리스트 CLEAR

SELECT * FROM TEST_NEW_TABLE;
SHOW TABLES;


CREATE TABLE MINICOUNTRY
	SELECT COUNTRY_ID, COUNTRY FROM COUNTRY
    WHERE COUNTRY LIKE 'S%';
SHOW TABLES;
SELECT * FROM MINICOUNTRY;

INSERT INTO MINICOUNTRY
	SELECT COUNTRY_ID, COUNTRY FROM COUNTRY
    WHERE COUNTRY LIKE 'R%' OR COUNTRY LIKE 'N%';
SELECT * FROM MINICOUNTRY;

DELETE FROM MINICOUNTRY WHERE COUNTRY = '';
SELECT * FROM NIMICOUNTRY;

DESC MINICOUNTRY;

-- UPDATE 체이블명 SET 바꿀 컬럼명 = 값 WHERE 조건식;



