SHOW databases;
SHOW DATABASES;
USE SAKILA;
SELECT DATABASE();
SHOW TABLES;
SELECT * FROM ACTOR;
SELECT NAME FROM CUSTOMER_LIST;
SELECT CEIL(RENTAL_RATE) AS RRCEIL FROM FILM ORDER BY TITLE;
SELECT * FROM CUSTOMER_LIST;
SELECT NAME, CITY FROM CUSTOMER_LIST;
DESC CUSTOMER_LIST;

# 문자열의 길이 계산 = CHAR_LENGTH
SELECT char_length(DESCRIPTION) FROM FILM;

# 문자열의 바이트 단위의 길이 계산 = OCTET_LENGTH
SELECT OCTET_LENGTH(DESCRIPTION) FROM FILM;

SELECT char_length('ABC');
SELECT char_length('가나다');
SELECT octet_length('ABC'); # 3바이트
SELECT octet_length('가나다'); # 왜 9바이트
# 알파벳 : 1글자 1바이트(반각문자) / 한글 : 1글자 3바이트(전각문자)

# 전각문자 - euc-kr 인코딩 : 2바이트 / utf-8 인코딩 : 3바이트

# 날짜 연산!
SELECT CURRENT_TIME();
SELECT CURRENT_TIMESTAMP();

SELECT CURRENT_DATE();
SELECT CURRENT_DATE() + INTERVAL 1 DAY;  # 내일
SELECT CURRENT_TIME() + INTERVAL 3 HOUR;
SELECT DAYOFWEEK(CURRENT_TIMESTAMP()); # 1(일) 금요일(6)
SELECT WEEKDAY(CURRENT_TIMESTAMP());  # 0(월) 

SELECT dayofmonth(current_timestamp());  # 월로 따졌을 때, 이번 달에 며칠 째
SELECT dayofYEAR(current_timestamp());  # 월로 따졌을 때, 이번 해에 며칠 째

SELECT MONTH(current_timestamp());  # 6월
SELECT DATE(current_timestamp());
SELECT YEAR(current_timestamp());

SELECT HOUR(current_timestamp());
SELECT MINUTE(current_timestamp());
SELECT SECOND(current_timestamp());


# 문자로 날짜 연산
SELECT dayname(CURRENT_TIMESTAMP());  # Friday

# 분기
select quarter(current_timestamp());

# 주
select week(current_timestamp());

# 데이터 변환
SELECT * FROM COUSTOMER_LIST;
SHOW TABLES;
SELECT COUNTRY, CASE WHEN COUNTRY = 'ALGERIA' THEN 'A'
ELSE 'B'
END
FROM CUSTOMER_LIST;

# NOTES 가 ACTIVE 면 1, 아니면 0으로 변환한 A_CODE열을 읽어보세요.
SELECT CASE WHEN NOTES = 'ACTIVE' THEN 1
ELSE 0
END AS A_CODE
FROM CUSTOMER_LIST;

SELECT COUNTRY,
	CASE
		WHEN COUNTRY = 'ALGERIA' THEN 'A'
		WHEN COUNTRY = 'BRAZIL' THEN 'B' 
		WHEN COUNTRY = 'CHINA' THEN 'C'
		ELSE 'ELSE'
	END AS COUNTRY_CODE
FROM CUSTOMER_LIST;

SELECT COUNTRY,
	CASE
		WHEN COUNTRY LIKE 'A%' THEN 'A'
		WHEN COUNTRY LIKE 'B%' THEN 'B' 
		WHEN COUNTRY LIKE 'C%' THEN 'C'
		ELSE 'ELSE'
	END AS COUNTRY_CODE
FROM
	CUSTOMER_LIST
    WHERE COUNTRY_CODE = 'A%' OR COUNTRY LIKE 'B%' OR COUNTRY LIKE 'C%'
    ORDER BY COUNTRY_CODE DESC, COUNTRY DESC
    LIMIT 5
    OFFSET 10;
    
    
SELECT * FROM FILM;
SELECT CASE WHEN ORIGINAL_LANGUAGE_ID IS NULL THEN 0 END
FROM FILM;

# NULL 처리
SELECT coalesce(ORIGINAL_LANGUAGE_ID, 0) FROM FILM;







